version: '3'

services:
  mongo:
    image: mongo
    ports:
    - "27018:27017"
    - "27017:27017"
  life2:
    build:
      context: .
      dockerfile: life2-app/life2-app-artifact/Dockerfile
    ports:
    - "11000:11000"
    links:
    - mongo
    - billshwah
    environment:
    - life2_email_billshwah_host=billshwah
  person.index:
    build:
      context: .
      dockerfile: life2-app/life2-app-person-index/Dockerfile
    volumes:
    - /Users/rich/life2/data:/data/life2/data
    links:
    - mongo
  person.index.2:
    build:
      context: .
      dockerfile: life2-app/life2-app-person-index/Dockerfile
    volumes:
    - /Users/rich/life2/data:/data/life2/data
    environment:
    - SPRING_PROFILES_ACTIVE=billshwah
    links:
    - mongo
  billshwah.index:
    build:
      context: .
      dockerfile: life2-app/life2-app-email-index/Dockerfile
    volumes:
    - /Users/rich/life2/data:/data/life2/data
    environment:
    - SPRING_PROFILES_ACTIVE=billshwah
    links:
    - mongo
  billshwah:
    build:
      context: .
      dockerfile: life2-app/life2-app-email/Dockerfile
    volumes:
    - /Users/rich/life2/data:/data/life2/data
    environment:
    - SPRING_PROFILES_ACTIVE=billshwah
    links:
    - mongo