version: '3.4'

x-extra:
  person.index:
    &person_index
    build:
      context: .
      dockerfile: life2-app/life2-app-person-index/Dockerfile
    volumes:
    - /Users/rich/life2/data:/data/life2/data
    links:
    - mongo

services:
  life2.index:
    << : *person_index